name = "Yipeee"
author = "AlexCode"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d07d1c8b602de278cbf7d1a09e1eda34984862198ac98a90bc99619a2c861eb9"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
