name = "Yipeee"
author = "AlexCode"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fdeeec87f63e5c9910255edaa9f017c4a5bcf447cbd82a70cce7a0299819591"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
