name = "Yipeee"
author = "AlexCode"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc4144f74138cc221c39d698390f5a87df0d6d193c33e2706ce89497d9976e3b"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
