#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Mon Mar 30 02:24:09 CEST 2026
alwaysLogTamperWarnings=true
